#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse

import mr.config.log
import mr.models.kv.invocation
import mr.models.kv.step
import mr.models.kv.queues.dataset

description = "Print the invocation-graph for a request"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')
parser.add_argument('invocation_id', help='Invocation ID')

args = parser.parse_args()

workflow = mr.models.kv.workflow.get(args.workflow_name)
invocation_id = args.invocation_id

while invocation_id is not None:
    invocation = mr.models.kv.invocation.get(workflow, invocation_id)
    step = mr.models.kv.step.get(workflow, invocation.step_name)

    if invocation.direction == mr.constants.D_MAP:
        handler_phrase = ('[%s]->[%s]' % 
                          (step.map_handler_name, step.combine_handler_name))
    elif invocation.direction == mr.constants.D_REDUCE:
        handler_phrase = ('[%s]' % (step.reduce_handler_name))
    else:
        raise ValueError("Invocation direction [%s] is not valid." % 
                         (invocation.direction,))

    dqa = mr.models.kv.queues.dataset.DatasetQueue(
        workflow, 
        invocation,
        mr.models.kv.queues.dataset.DT_ARGUMENTS)

    try:
        dqa.list_data()
    except KeyError:
        has_arguments = True
    else:
        has_arguments = False

    dqr = mr.models.kv.queues.dataset.DatasetQueue(
        workflow, 
        invocation,
        mr.models.kv.queues.dataset.DT_POST_REDUCE)

    try:
        dqr.list_data()
    except KeyError:
        has_results = True
    else:
        has_results = False

    direction_aligned = '[%s]' % invocation.direction

    print("Invocation: [%s] %8s %50s A=[%s] R=[%s] P=[%s]" % 
          (invocation.invocation_id, direction_aligned, handler_phrase,
           has_arguments, has_results, invocation.parent_invocation_id))

    invocation_id = invocation.parent_invocation_id
