#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.workflow

description = "Create a workflow entity"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('name', help='Name')
parser.add_argument('description', help='Description')

args = parser.parse_args()

w = mr.models.kv.workflow.Workflow(
        workflow_name=args.name, 
        description=args.description, 
        handlers_state='')

w.save()

print(w.get_debug())
