#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.workflow
import mr.models.kv.step

description = "Get a workflow entity"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')
parser.add_argument('step_name', help='New step name')

args = parser.parse_args()

w = mr.models.kv.workflow.WorkflowKv()
workflow = w.get_workflow_by_name(args.workflow_name)

s = mr.models.kv.step.StepKv()
step = s.get_step_by_workflow_and_name(workflow, args.step_name)

pprint.pprint(step)
