#!/usr/bin/env python3

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse

import mr.config.log
import mr.models.kv.workflow

description = "Create a workflow entity"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('name', help='Name')
parser.add_argument('description', help='Description')

args = parser.parse_args()

w = mr.models.kv.workflow.WorkflowKv()
w.create_workflow(args.name, args.description)
