#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.workflow
import mr.models.kv.job
import mr.models.kv.request

description = "Create a request entity"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')
parser.add_argument('job_name', help='Job name')

parser.add_argument('-a', '--argument', 
                    required=True, action='append', nargs=2, help='Argument')

parser.add_argument('-c', '--context', help='Context information')

args = parser.parse_args()

workflow = mr.models.kv.workflow.get(args.workflow_name)
job = mr.models.kv.job.get(workflow, args.job_name)

r = mr.models.kv.request.Request(
        workflow=workflow, 
        job_name=job.job_name, 
        arguments=dict(args.argument), 
        context=args.context)

r.save()

pprint.pprint(r)
