#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.workflow
import mr.models.kv.step

description = "Get a step entity"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')
parser.add_argument('step_name', help='Step name')

args = parser.parse_args()

workflow = mr.models.kv.workflow.get(args.workflow_name)
step = mr.models.kv.step.get(workflow, args.step_name)

# TODO(dustin): We should verify that no jobs are currently hooked to this 
#               step.

step.delete()
