#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint
import select

import mr.config.log
import mr.models.kv.workflow
import mr.models.kv.step

description = "Create a step entity"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')
parser.add_argument('name', help='Name')
parser.add_argument('description', help='Description')
parser.add_argument('code_type', help='Code language')

parser.add_argument('-a', '--argument', 
                    required=True, 
                    action='append', 
                    nargs=2, 
                    help='Argument name and type (must be valid)')

args = parser.parse_args()

stdin_waiting = select.select([sys.stdin], [], [], 0)[0]
if not stdin_waiting:
    print("Please provide code via STDIN.")
    sys.exit(1)

code_body = sys.stdin.read().strip()

workflow = mr.models.kv.workflow.Workflow.get_by_name(args.workflow_name)

r = mr.models.kv.step.Step.create(
        workflow, 
        args.name, 
        args.description, 
        dict(args.argument), 
        (args.code_type, code_body))

pprint.pprint(r)
