#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.workflow
import mr.models.kv.step

description = "Get all steps entities for a workflow"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')

args = parser.parse_args()

w = mr.models.kv.workflow.WorkflowKv()
workflow = w.get_by_name(args.workflow_name)

s = mr.models.kv.step.StepKv()
steps = s.get_all_by_workflow(workflow)

for step in steps:
    pprint.pprint(step)
