#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.job
import mr.models.kv.workflow

description = "List a job entities for a workflow"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')

args = parser.parse_args()

workflow = mr.models.kv.workflow.get(args.workflow_name)
jobs = mr.models.kv.job.Job.list(workflow.workflow_name)
jobs = list(jobs)

for job in sorted(jobs, key=lambda j: j.job_name):
    print(job.job_name + ':')
    print('')

    pprint.pprint(job.get_data())
    print('')
