#!/usr/bin/env python3

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.workflow
import mr.models.kv.job

description = "Create a invoked-workflow entity"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')
parser.add_argument('job_name', help='Job name')

parser.add_argument('-c', '--context', help='Context information')

args = parser.parse_args()

w = mr.models.kv.workflow.WorkflowKv()
workflow = w.get_by_name(args.workflow_name)

j = mr.models.kv.job.JobKv()
job = j.get_by_workflow_and_name(workflow, args.job_name)

iw = mr.models.kv.workflow.InvokedWorkflowKv()
r = iw.create_invoked_workflow(workflow, job, args.context)

pprint.pprint(r)
