#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.workflow
import mr.models.kv.handler

description = "Get a handler entity"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')
parser.add_argument('handler_name', help='Handler name')

args = parser.parse_args()

workflow = mr.models.kv.workflow.get(args.workflow_name)
handler = mr.models.kv.handler.get(workflow, args.handler_name)
handler.delete()
