#!/usr/bin/env python2.7

import sys
import os.path
dev_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, dev_path)

import argparse
import pprint

import mr.config.log
import mr.models.kv.workflow
import mr.models.kv.handler

description = "Get all handlers entities for a workflow"

parser = argparse.ArgumentParser(description=description)

parser.add_argument('workflow_name', help='Workflow name')

args = parser.parse_args()

workflow = mr.models.kv.workflow.get(args.workflow_name)
handlers = mr.models.kv.handler.Handler.list(workflow.workflow_name)

for handler in handlers:
    print(handler.get_debug(ignore_keys=('source_code',)))
